<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php 
        /** Getting Order Items */
        ?>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php
         echo $this->getUrl('sales/order/history') ?>"><?php
          echo $this->__('View All') ?></a><?php
           endif; ?>
    </div>
    <?php 
    /** 
     * Getting size of order items
     */
    
    ?>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table class="data-table orders" id="my-orders-table">
    <col width="1" /><col width="1" />
    <col /><col width="1" />
    <col width="1" /><col width="1" />
        <thead>
            <tr>
                <th class="number"><?php echo $this->__('Order #') ?></th>
                <th class="date"><?php echo $this->__('Date') ?></th>
                <th class="ship"><?php echo $this->__('Ship To') ?></th>
                <th class="total"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                <th class="status"><?php echo $this->__('Status') ?></th>
                <th class="view">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                <?php 
                /** 
                 * get order id 
                 */
                ?>
                    <td class="number"><?php echo $_order->getRealOrderId() ?></td>
                    <?php 
                    /**
                     * get created date
                     */
                    ?>
                    <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <?php 
                    /**
                     * get shipping address
                     */
                    ?>
                    <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <?php 
                    /**
                     * getting grand total
                     */
                    ?>
                    <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <?php 
                    
                    /** get status label */
                    ?>
                    <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center view">
                        <span class="nobr">
                        <?php 
                        
                        /**
                         * get view url
                         */
                        ?>
                        <a href="<?php echo $this->getViewUrl($_order) ?>"><?php
                         echo $this->__('View Order') ?></a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span>
                            <?php 
                            /** 
                             * reorder url 
                             * */
                               ?>
                             <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php
                             echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
