<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="box-account box-info">
    <div class="box-head">
        <h2><?php echo $this->__('Address Book') ?></h2>
        <a href="<?php echo $this->getAddressBookUrl() ?>">
        <?php echo $this->__('Manage Addresses') ?></a>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Billing Address') ?></h3>
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>">
                    <?php echo $this->__('Edit Address') ?></a>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryBillingAddressHtml() ?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>">
                    <?php echo $this->__('Edit Address') ?></a>
                </div>
                <div class="box-content">
                    <address><?php echo $this->getPrimaryShippingAddressHtml() ?></address>
                </div>
            </div>
        </div>
    </div>
</div>
