<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="page-title">
        <h1 class="manage_zipcodes_head"><?php echo $this->__('Manage Zipcodes') ?></h1>
      
    </div>
    
      <button onclick="window.location='<?php echo Mage::helper('marketplace/outofstock')->getZipcodeUrl(); ?>';" title="<?php
     echo $this->__('Add New Zipcode'); ?>" class="button right mp_addnew_pdt"> <span><span><?php
     /**
      * Display add new product option
      */
     echo $this->__('Add New Zipcode'); ?> </span></span></button>
<?php $_zipCodes = $this->getCollection(); 
if( count ( $_zipCodes )>0){
?>
<table class="zipcode-manage-table data-table" id="zipcode_manage">

	<thead>
		<tr>
			<th><?php echo $this->__('Identification');?></th>
		
			<th><?php echo $this->__('Country');?></th>
		
			<th><?php echo $this->__('State');?></th>
		
			<th><?php echo $this->__('City');?></th>
		
			<th><?php echo $this->__('Range');?></th>
		
			<th><?php echo $this->__('Exception');?></th>
		
			<th><?php echo $this->__('Action');?></th>
			<th><?php echo $this->__('');?></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($_zipCodes as $zipCodeData){?>
		<tr>
			<td><?php echo $zipCodeData->getZipcodeId();?></td>
			<td><?php echo $zipCodeData->getCountry();?></td>
			<td><?php echo $zipCodeData->getState();?></td>
			<td><?php echo $zipCodeData->getCity();?></td>
			<td><?php echo $zipCodeData->getSellerZipcodeRange();?></td>
			<td><?php echo $zipCodeData->getSellerZipcodeExp();?></td>
			<td><a href="<?php echo Mage::getUrl('marketplace/zipcode/zipcodeforseller/id/'.$zipCodeData->getId())?>"><?php echo $this->__("Edit");?></a></td>
		<td><a href="<?php echo Mage::getUrl('marketplace/zipcode/zipcodedelete/id/'.$zipCodeData->getId())?>"><?php echo $this->__("Edit");?></a></td>
		</tr>
	<?php }?>
	</tbody>
</table>
<?php }else{?>

	
	<h5><?php echo $this->__('No Records Found');?></h5>
<?php }?>