<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
/**
 *  @var $this Mage_Catalog_Block_Product_Compare_List 
*/
?>
<div class="page-title title-buttons">
    <h1><?php 
    /**
     * Display compare products title
     */
    echo $this->__('Compare Products') ?></h1>
    <a href="#" onclick="window.print(); return false;" class="link-print"><?php
    /**
     * Display Print option
     */
    echo $this->__('Print This Page') ?></a>
</div>
<?php 
/**
 * Get Total items count
 */
$_total=$this->getItems()->count() ?>
<?php 
/**
 * check total has been set
 */
if($_total): ?>
    <table class="data-table compare-table" id="product_comparison">
        <?php $_i=0 ?>
        <?php foreach($this->getItems() as $_item): ?>
            <?php 
            $_i++;
            if($_i%10==0): ?>
                <col width="1" />
            <?php endif; ?>
            <col width="<?php echo floor(100/$_total); ?>%" />
        <?php endforeach; ?>
        <?php if ($_total>2): ?>
            <thead>
            <tr>
                <?php $_i=0 ?>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php 
                    $_i++;
                    if($_i%10==0): ?>
                        <th>&nbsp;</th>
                    <?php endif; ?>
                    <td class="a-right"><a href="#" class="btn-remove" onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');" 
                    title="<?php echo $this->__('Remove This Item') ?>">
                    <?php 
                    /**
                     * Display Remove Item option
                     */
                    echo $this->__('Remove This Item') ?></a></td>
                <?php endforeach; ?>
            </tr>
            </thead>
        <?php endif ?>
        <tbody>
        <tr class="product-shop-row top">
            <?php $_i=0 ?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php 
                $_i++;
                if($_i%10==0): ?>
                    <th>&nbsp;</th>
                <?php endif; ?>
                <td>
                    <a class="product-image" href="#" onclick="setPLocation('<?php echo $this->getProductUrl($_item) ?>', true)" 
                    title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>" width="125" height="125" 
                    alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" /></a>
                    <h2 class="product-name"><a href="#" onclick="setPLocation('<?php echo $this->getProductUrl($_item) ?>', true)" 
                    title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                    <?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></h2>
                    <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                    <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
                </td>
            <?php endforeach; ?>
        </tr>
        <tr class="product-shop-row bottom">
            <?php $_i=0 ?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php 
                $_i++;
                if($_i%10==0): ?>
                    <th>&nbsp;</th>
                <?php endif; ?>
                <td>
                    <?php 
                    /**
                     * check the product item is saleable
                     * if so display add to cart option
                     * else show the out of stock information
                     */
                    if($_item->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" 
                        onclick="setPLocation('<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>', true)">
                        <span><span><?php
                         echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <?php 
                    /**
                     * Check the wishlist option allowed for the product
                     * if so show add to wishlist option for the product
                     */
                    if ($this->helper('wishlist')->isAllow()) : ?>
                        <ul class="add-to-links">
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist">
                            <?php echo $this->__('Add to Wishlist') ?></a></li>
                        </ul>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
        </tr>
        </tbody>
        <tbody>
        <?php foreach ($this->getAttributes() as $_attribute): ?>
            <tr>
                <?php $_i=0 ?>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php 
                    $_i++;
                    if($_i%10==0): ?>
                        <th><span class="nobr"><?php echo $_attribute->getStoreLabel() ?></span></th>
                    <?php endif; ?>
                    <td>
                        <?php switch ($_attribute->getAttributeCode()) {
                            /**
                             * Check the attribute code is price
                             */
                            case "price": ?>
                                <?php echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode()) ?>
                                <?php break;
                            /**
                            * Check the attribute code is small image
                            */
                            case "small_image": ?>
                                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>" width="125" height="125" 
                                alt="<?php echo $this->escapeHtml($_item->getName()) ?>" 
                                title="<?php echo $this->escapeHtml($_item->getName()) ?>" />
                                <?php break;
                            /**
                            * Check the attribute code is date
                            */
                            case "date":
                                echo substr($this->getProductAttributeValue($_item, $_attribute),0,10);
                                break;
                            default: ?>
                                <div class="std">
                                    <?php
                                    echo '<strong>'.ucwords(str_replace('_',' ',$_attribute->getName())).' : </strong><br/>';
                                    echo $this->helper('catalog/output')->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                </div>
                            <?php break;
                        } ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tbody>
        <tr class="add-to-row">
            <?php $_i=0 ?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php 
                $_i++;
                if($_i%10==0): ?>
                    <th>&nbsp;</th>
                <?php endif; ?>
                <td>
                    <?php 
                    echo '<strong>'.$this->__('Price').' : </strong><br/>';
                    echo $this->getPriceHtml($_item, true, '-compare-list-bottom') ?>
                    <?php 
                    /**
                     * Check product is saleable product
                     * if so display add to cart option
                     * else out of stock information
                     */
                    if($_item->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" 
                        onclick="setPLocation('<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>', true)">
                        <span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <ul class="add-to-links">
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_item);?>" class="link-wishlist">
                            <?php echo $this->__('Add to Wishlist') ?></a></li>
                        </ul>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
        </tr>
        </tbody>
    </table>
    <div class="buttons-set">
        <button type="button" title="<?php echo $this->__('Close Window') ?>" class="button" onclick="window.close();">
        <span><span><?php echo $this->__('Close Window') ?></span></span></button>
        <span class="please-wait" id="compare-list-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" 
            alt="<?php echo $this->__('Please wait...') ?>" 
            title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> 
            <?php echo $this->__('Please wait...') ?>
        </span>
    </div>
    <script type="text/javascript">
        decorateTable('product_comparison');

        /**
         * Send remove item request, after that reload windows
         */
        function removeItem(url)
        {
            new Ajax.Request(url, {
                parameters: {isAjax: 1, method: 'POST'},
                onLoading: function(){$('compare-list-please-wait').show();},
                onSuccess: function(transport) {
                    $('compare-list-please-wait').hide();
                    window.location.reload();
                    window.opener.location.reload();
                }
            });
        }
    </script>
<?php else: ?>
    <script type="text/javascript">window.close();</script>
<?php endif; ?>
