<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */
?>
<?php
$prodCount=null;
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<?php if($_helper->getItemCount() > 0) { ?>

<div class="block block-list block-compare">
<?php } else  { ?>
<div class="block block-list block-compare" style ="display: none">
<?php }?>
<div class="righttop" id="addClass" onclick="expandColapseCompareSection();"><span></span></div>
<div class ="minimize" style ="display: none">

 <div class="block-title">
 
        <strong><span><?php echo $this->__('My Compared Products') ?>
            <?php if($_helper->getItemCount() > 0): ?>
                <small><?php echo $this->__('(%d)', $_helper->getItemCount()) ?></small>
            <?php endif; ?>
        </span></strong>
    
    </div>
    <div class="block-content">
    
    <?php if($_helper->getItemCount() > 0): 
    $prodCount =0;
    ?>
        <ul id="compare-items" >
        <?php foreach($_items as $_index => $_item):
          $prodCount++;
        
        if($prodCount < 5) {
        ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="javascript:void(0)" onclick='ajaxRemove("<?php echo $_helper->getRemoveUrl($_item) ?>")' title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"></a>
                <?php
		$productid = $_item->getId();
		$model = Mage::getModel('catalog/product'); //getting product model
		$_product = $model->load($productid); //getting product object for particular product id
        $url = $_product->getProductUrl();
		?>
		        <p class="product-image"><a href="<?php echo $url ?>"> <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(106, 44); ?>"/></a></p>
		                    
            </li>
        <?php }endforeach; ?>
        </ul>
        
        <script type="text/javascript">decorateList('compare-items')</script>
        
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
    <?php endif; ?>
    </div>
	<div class="actions">
			<?php if($prodCount > 4) {?>
	        <p class="show-all"><a href="javascript:void(0)" onclick='showAll()' title="<?php echo $this->__('Show All') ?>" class="show-all" ><?php echo $this->__('Show All') ?></a></p>
	        <?php }?>
            <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" 
            onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">
            <span><span><?php echo $this->__('Compare') ?></span></span></button>
            <a href="javascript:void(0)" onclick='ajaxClear("<?php echo $_helper->getClearListUrl(); ?>")'
            onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');" title="Clear All" >
            <?php echo $this->__('Clear All') ?></a>
        </div>
</div>
<div class ="add">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Compared Products') ?>
            <?php if($_helper->getItemCount() > 0): ?>
                <small><?php echo $this->__('(%d)', $_helper->getItemCount()) ?></small>
            <?php endif; ?>
        </span></strong>
        <a href="javascript:void(0)" onclick='ajaxClear("<?php echo $_helper->getClearListUrl(); ?>")'
            onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');" >
            <?php echo $this->__('Clear All') ?></a>
    </div>
    <div style="color:red"><div class="compare-success-message"></div></div>
    <div class="block-content">
    <?php if($_helper->getItemCount() > 0): ?>
        <ol id="compare-items" class="slider-images">
        <?php foreach($_items as $_index => $_item): ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="javascript:void(0)" onclick='ajaxRemove("<?php echo $_helper->getRemoveUrl($_item) ?>")' title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"></a>
                <?php
		$productid = $_item->getId();
		$model = Mage::getModel('catalog/product'); //getting product model
		$_product = $model->load($productid); //getting product object for particular product id
        $url = $_product->getProductUrl();
		?>
		        <p class="product-image"><a href="<?php echo $url ?>"> <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(91, 68); ?>"/></a></p>
		                    
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>">
                <?php $str = ucwords($this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name'));
			              				if (strlen($str) > 35)
			              					$str = substr($str, 0, 35) . '...';
			    ?>
                <?php echo $str ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('compare-items')</script>
        <div class="actions">
            <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" 
            onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')">
            <span><span><?php echo $this->__('Compare') ?></span></span></button>
          
        </div>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
    <?php endif; ?>
    </div>
    </div>
</div>
<script>
jQuery('.slider-images').bxSlider({
	infiniteLoop:false,
	hideControlOnEnd:true,
    slideWidth: 220,
    minSlides: 1,
    maxSlides: 3,
    moveSlides: 1,
    slideMargin: 5
  });

		
</script>
