<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<?php if(count($this->getStores())>1): ?>
<div class="form-language form_lang_main">
<div class="form-language">
    <label for="select-language"><?php echo $this->__('Your Language:') ?></label>
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
       <?php if($_selected	){?>
        <div class="language"><?php echo $this->escapeHtml($_lang->getName()) ?></div>
        
        <?php }?>
    <?php endforeach; ?>
    <span></span>
 </div>
<?php endif; 
/**
 * Check if the store is available or not
 */
?>
<?php if(count($this->getStores())>1): ?>
<div class="form-language form_lang_sub">
    <label for="select-language"><?php echo $this->__('Your Language:') ?></label>
    <ul id="select-language" title="<?php echo $this->__('Your Language') ?>" onchange="window.location.href=this.value">
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <li class="<?php echo $_lang->getName();?>" value="<?php echo $_lang->getCurrentUrl() ?>"<?php echo $_selected ?>>
        <a href="<?php echo $_lang->getCurrentUrl(); ?>">
         <?php echo $this->escapeHtml($_lang->getName()); ?>
         </a>
         </li>
    <?php 
    /**
     * End foreach
     */
    endforeach; ?>
    </ul>
</div>
<?php 
/**
 * If condition is end
 */
endif; ?>
</div>