<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>

<form action="" id="co-shipping-form">
	<ul class="form-list">
    <?php
				/**
				 * Check the customer has address
				 */
				if ($this->customerHasAddresses ()) :
					?>
       <li class="wide"><label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
			<div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping')?>
           </div></li>
    <?php endif ?>
        <li id="shipping-new-address-form"
			<?php
			/**
			 * Check the customer has address
			 */
			if ($this->customerHasAddresses ()) :
				?>
			style="display: none;" <?php endif ?> class="scaffold-form">
			<div class="fieldset">
				<p class="required"><?php echo $this->__('* Required Fields') ?></p>
				<input type="hidden" name="shipping[address_id]"
					value="<?php echo $this->getAddress()->getId() ?>"
					id="shipping:address_id" />
				<ul>
					<li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
					<li class="fields">
						<div class="fields">
							<label for="shipping:company"><?php echo $this->__('Company') ?></label>
							<div class="input-box">
								<input type="text" id="shipping:company"
									name="shipping[company]"
									value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
									title="<?php echo $this->__('Company') ?>"
									class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>"
									onchange="shipping.setSameAsBilling(false);" />
							</div>
						</div>
					</li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide"><label for="shipping:street1"
						class="required"><em>*</em><?php echo $this->__('Address') ?></label>
						<div class="input-box">
							<input type="text"
								title="<?php echo $this->__('Street Address') ?>"
								name="shipping[street][]" id="shipping:street1"
								value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
								class="input-text <?php echo $_streetValidationClass ?>"
								onchange="shipping.setSameAsBilling(false);" />
						</div></li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide"><label
						for="billing:street<?php echo $_i ?>">
                        <?php echo $this->__('Address') ?> 
                        <?php echo $_i ?></label>
						<div class="input-box">
							<input type="text"
								title="<?php echo $this->__('Street Address %s', $_i) ?>"
								name="shipping[street][]" id="shipping:street<?php echo $_i ?>"
								value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
								class="input-text <?php echo $_streetValidationClass ?>"
								onchange="shipping.setSameAsBilling(false);" />
						</div></li>
            <?php endfor; ?>
                    <?php
																				/**
																				 * Check the customer address vat attribute is visible
																				 * if so display vat number
																				 */
																				if ($this->helper ( 'customer/address' )->isVatAttributeVisible ()) :
																					?>
                    <li class="wide"><label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
						<div class="input-box">
							<input type="text" id="shipping:vat_id" name="shipping[vat_id]"
								value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>"
								title="<?php echo $this->__('VAT Number'); ?>"
								class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
						</div></li>
                    <?php endif; ?>
                    <li class="fields">
						<div class="field">
							<label for="shipping:city" class="required"><em>*</em><?php
							/**
							 * Display City field
							 */
							echo $this->__ ( 'City' )?></label>
							<div class="input-box">
								<input type="text" title="<?php echo $this->__('City') ?>"
									name="shipping[city]"
									value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
									class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
									id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
							</div>
						</div>
						<div class="field">
							<label for="shipping:region" class="required"><em>*</em><?php
							/**
							 * Display State or province field
							 */
							echo $this->__ ( 'State/Province' )?></label>
							<div class="input-box">
								<select id="shipping:region_id" name="shipping[region_id]"
									title="<?php echo $this->__('State/Province') ?>"
									class="validate-select" style="display: none;">
									<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
								</select>
								<script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
								<input type="text" id="shipping:region" name="shipping[region]"
									value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
									title="<?php echo $this->__('State/Province') ?>"
									class="input-text <?php
									echo $this->helper ( 'customer/address' )->getAttributeValidationClass ( 'region' )?>"
									style="display: none;" />
							</div>
						</div>
					</li>
					<li class="fields">
						<div class="field">
							<label for="shipping:postcode" class="required"><em>*</em><?php
							/**
							 * Display zip or postal code
							 */
							echo $this->__ ( 'Zip/Postal Code' )?></label>
							<div class="input-box">
								<input type="text"
									title="<?php echo $this->__('Zip/Postal Code') ?>"
									name="shipping[postcode]" id="shipping:postcode"
									value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
									class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
									onchange="shipping.setSameAsBilling(false);" />
							</div>
						</div>
						<div class="field">
							<label for="shipping:country_id" class="required"><em>*</em><?php
							/**
							 * Display country field
							 */
							echo $this->__ ( 'Country' )?></label>
							<div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping')?>
                            </div>
						</div>
					</li>
					<li class="fields">
						<div class="field">
							<label for="shipping:telephone" class="required"><em>*</em><?php
							/**
							 * Display Telephone field
							 */
							echo $this->__ ( 'Telephone' )?></label>
							<div class="input-box">
								<input type="tel" name="shipping[telephone]"
									value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
									title="<?php echo $this->__('Telephone') ?>"
									class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
									id="shipping:telephone"
									onchange="shipping.setSameAsBilling(false);" />
							</div>
						</div>
						<div class="field">
							<label for="shipping:fax"><?php
							/**
							 * Display Fax field
							 */
							echo $this->__ ( 'Fax' )?></label>
							<div class="input-box">
								<input type="tel" name="shipping[fax]"
									value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
									title="<?php echo $this->__('Fax') ?>"
									class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
									id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
							</div>
						</div>
					</li>
                <?php
																/**
																 * Check the Customer is currently logged in
																 * and the customer has addresses for him
																 */
																if ($this->isCustomerLoggedIn () && $this->customerHasAddresses ()) :
																	?>
                    <li class="control"><input type="checkbox"
						name="shipping[save_in_address_book]" value="1"
						title="<?php echo $this->__('Save in address book') ?>"
						id="shipping:save_in_address_book"
						onchange="shipping.setSameAsBilling(false);"
						<?php if ($this->getAddress()->getSaveInAddressBook()):?>
						checked="checked" <?php endif;?> class="checkbox" /><label
						for="shipping:save_in_address_book">
                        <?php
																	/**
																	 * Display option to save the current address in address book
																	 */
																	echo $this->__ ( 'Save in address book' )?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden"
						name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
			</div>
		</li>
		<li class="control"><input type="checkbox"
			name="shipping[same_as_billing]" id="shipping:same_as_billing"
			value="1" <?php if($this->getAddress()->getSameAsBilling()): ?>
			checked="checked" <?php endif; ?>
			title="<?php echo $this->__('Use Billing Address') ?>"
			onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label
			for="shipping:same_as_billing">
            <?php
												/**
												 * Display option to use the current address as billing address
												 */
												echo $this->__ ( 'Use Billing Address' )?></label></li>
	</ul>
	<div class="buttons-set" id="shipping-buttons-container">
		<p class="back-link">
			<a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
		</p>
		<button type="button" class="button"
			title="<?php echo $this->__('Continue') ?>" onclick="shipping.save()">
			<span><span><?php echo $this->__('Continue') ?></span></span>
		</button>
		<span id="shipping-please-wait" class="please-wait"
			style="display: none;"> <img
			src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
			alt="<?php echo $this->__('Loading next step...') ?>"
			title="<?php echo $this->__('Loading next step...') ?>"
			class="v-middle" /> 
            <?php echo $this->__('Loading next step...')?>
        </span>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', 
        '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
<?php
$enableZipcodeValidation = Mage::getStoreConfig ( "marketplace/product/zipcode_validation" );
if ($enableZipcodeValidation == 1) {
	?>

<script>
var $jq = jQuery.noConflict();
$jq("#shipping-buttons-container").click(function(){

	 var addressid=$jq("#shipping-address-select").val();
	  if($jq("#shipping-address-select").length && addressid!=''){
			$jq.ajax({
	   	    type: 'POST',
	   	    dataType: "json",
	   	    url: '<?php echo $this->getUrl('onestepcheckout/onepage/getonestepbillingid'); ?>',
	   	    data: { 
	   	        'billingid': addressid 
	   	    },success: function(data){
	   	    	checkData(data);

	   	    	
	   	     }

		});

		}
	  else{
		  checkData($('shipping:postcode').value);
	  }
	});

function checkData(data){
	if (($jq('#response-data').length)) {
   	    $jq('#response-data').remove();
   	}
 	if (($jq('#response-shipping').length)) {
 		$jq('#response-shipping').remove();
   	}
	
	$jq.ajax({
	    type: 'POST',
	    dataType: "json",
	    url: '<?php echo $this->getUrl('onestepcheckout/onepage/saveBillingQuote'); ?>',
	    data: { 
	        'zipcode': data,
	        'address_id':$jq('#shipping-address-select').val(), 
	    },success: function(data){
				if(data.error==1 || data.error==2){
		    		 $jq("#co-shipping-method-form").prepend("<div id='response-shipping'>"+data.message+"</div>");
					$jq('#response-shipping').css('color','red');
				  }
				if(data.error==1 || data.error==2){
					document.getElementById("shipping-method-buttons-container").style.display = "none";
				}
		  		else{
			  		document.getElementById("shipping-method-buttons-container").style.display = "block";
				}
	    }
	});
}
</script>
<?php }?>