<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php 
$_item = $this->getItem()?>
<tr>
    <td><h3 class="product-name"><?php echo $this->escapeHtml($this->getProductName()) ?></h3>
        <?php if ($_optionsDetails = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_optionsDetails as $_option) : ?>
            <?php $_formatedOptionValueList = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValueList['full_view'])): ?> class="truncated"<?php endif; ?>>
            <?php echo $_formatedOptionValueList['value'] ?>
                <?php if (isset($_formatedOptionValueList['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionValueList['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
        <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
    </td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right" data-rwd-label="<?php echo $this->__('Price') ?>">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
            <?php else:
             ?>
                <?php
                 echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
            <?php
             endif;
              ?>
  </span>
  <?php if (Mage::helper('weee')->getApplied($_item)): ?>
 <div class="cart-tax-info" 
 id="eunit-item-tax-details<?php
  echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php
                     foreach (Mage::helper('weee')->getApplied($_item) as $taxpriceData): 
                     ?>
                        <span class="nobr">
                        <?php 
                        echo $taxpriceData['title']; 
                        ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($taxpriceData['amount'],true,true); ?></span><br />
                    <?php 
                    endforeach; 
                    ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php
                     foreach (Mage::helper('weee')->getApplied($_item) as $taxpriceInfo): ?>
                        <span class="nobr">
                        <small><?php echo $taxpriceInfo['title']; ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($taxpriceInfo['amount'],true,true); ?></small></span><br />
                    <?php 
                    endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php 
                    foreach (Mage::helper('weee')->getApplied($_item) as $taxpriceList): ?>
                        <span class="nobr">
                        <?php 
                        echo $taxpriceList['title']; ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($taxpriceList['amount'],true,true); ?></span><br />
                    <?php 
                    endforeach; ?>
                    </small>
                <?php
 }
  ?></div>
 <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" 
                onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr">
                    <?php 
                    echo Mage::helper('weee')->__('Total');
                     ?>:
                    <br /> 
                    <?php
                     echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); 
                     ?>
                     </span>
                </div>
            <?php endif;
             ?>
        <?php endif;
         ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td data-rwd-label="<?php echo $this->__('Price') ?>">
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total"
             onclick="taxToggle('unit-item-tax-details<?php 
             echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php 
            if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
            <?php 
            else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
            <?php 
            endif; ?>

        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" 
             style="display:none;"
             id="unit-item-tax-details<?php echo $_item->getId(); ?>">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php
                     foreach (Mage::helper('weee')->getApplied($_item) as $taxamtList):
                      ?>
                        <span class="nobr">
                        <?php 
                        echo $taxamtList['title']; 
                        ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($taxamtList['amount_incl_tax'],true,true); ?></span><br />
                    <?php 
                    endforeach;
                     ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php 
                    foreach (Mage::helper('weee')->getApplied($_item) as $taxAmtData):
                     ?>
                        <span class="nobr">
                        <small>
                        <?php
                         echo $taxAmtData['title']; ?>: 
                        <?php
                         echo Mage::helper('checkout')->formatPrice($taxAmtData['amount_incl_tax'],true,true); ?>
                         </small>
                         </span>
                         <br />
                    <?php
                     endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php 
                    foreach (Mage::helper('weee')->getApplied($_item) as $taxData):
                     ?>
                        <span class="nobr">
                        <?php 
                        echo $taxData['title'];
                         ?>: 
                        <?php
                         echo Mage::helper('checkout')->formatPrice($taxData['amount_incl_tax'],true,true); ?>
                         </span>
                         <br />
                    <?php 
                    endforeach; ?>
                    </small>
                <?php } ?>
            </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" 
                onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr">
                    <?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:
                    <br /> 
                    <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <td class="a-center" 
    data-rwd-label="<?php echo $this->__('Qty') ?>">
    <?php echo $_item->getQty() ?>
    </td>
    <!-- sub total starts here -->
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right" 
    data-rwd-label="<?php echo $this->__('Subtotal') ?>">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" 
            onclick="taxToggle('esubtotal-item-tax-details<?php 
            echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
     <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php 
                echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php 
                echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>
   </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" 
            id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" 
            style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php
                     foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <?php echo $tax['title']; ?>: 
                        <?php
                         echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php
                     endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php 
                    foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <small>
                        <?php echo $tax['title']; ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php 
                    foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <?php echo $tax['title'];
                         ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?></small>
                <?php } ?></div>
<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" 
                onclick="taxToggle('esubtotal-item-tax-details<?php 
                echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr">
                    <?php echo Mage::helper('weee')->__('Total'); ?>:
                    <br /> 
                    <?php
                     echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td data-rwd-label="<?php 
    echo $this->__('Subtotal') ?>">
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" 
            onclick="taxToggle('subtotal-item-tax-details<?php 
            echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
  <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php 
                echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
            <?php 
            else: ?>
                <?php 
                echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
            <?php 
            endif; ?>
  </span>
  <?php if (Mage::helper('weee')->getApplied($_item)): ?>
    <div class="cart-tax-info" 
    id="subtotal-item-tax-details<?php 
    echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr">
                        <?php
                         echo $tax['title']; ?>: 
                        <?php
                         echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php
                     foreach (Mage::helper('weee')->getApplied($_item) as $tax):
                     ?>
                        <span class="nobr">
                        <small>
                        <?php
                         echo $tax['title']; ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?>
                        </small>
                        </span>
                        <br/>
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ 
?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $taxDetail): 
                    ?>
                        <span class="nobr">
                        
                        
                        <?php
                         echo $taxDetail['title']; ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($taxDetail['row_amount_incl_tax'],true,true); ?>
                        </span>
                        <br />
                    <?php
                     endforeach; ?>
                    </small>
                <?php } ?>
            </div>

            <?php 
            if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): 
            ?>
                <div 
                 onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');"
                 class="cart-tax-total">
                    <span class="nobr">
                    <?php 
                    echo Mage::helper('weee')->__('Total incl. tax'); ?>:
                    <br /> 
                    <?php 
                    echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
</tr>
