<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<form name="validation_form" id="validation_form" action="<?php echo $this->getAcsUrl();?>" method="post">
    <div class="fieldset">
        <input type="hidden" name="PaReq" value="<?php echo $this->getPaReq()?>" />
        <input type="hidden" name="TermUrl" value="<?php echo $this->getTermUrl()?>" />
        <input type="hidden" name="MD" value="<?php echo $this->getMd()?>" />
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
window.onload = function(){
    document.getElementById('validation_form').submit();
};
//]]>
</script>
