<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
/* @var $this Mage_Wishlist_Block_Customer_Sidebar */
?>

<div class="block block-wishlist">
    <div class="block-title">
        <strong><span><?php echo $this->getTitle(); ?></span></strong>
    </div>
    <div class="block-content">
    <p class="block-subtitle"><?php echo $this->__('Last Added Items') ?></p>
    <?php if ($this->hasWishlistItems()): ?>
    <ol class="mini-products-list" id="wishlist-sidebar">
     <?php foreach ($this->getWishlistItems() as $_item): ?>
        <?php $product = $_item->getProduct(); ?>
        <li class="item">
            <a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php
             echo $this->escapeHtml($product->getName()) ?>" class="product-image">
             <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(50); ?>" width="50" height="50" alt="<?php
              echo $this->escapeHtml($product->getName()) ?>" /></a>
            <div class="product-details">
                <a href="<?php echo $this->getItemRemoveUrl($_item) ?>" title="<?php
                 echo $this->__('Remove This Item') ?>" onclick="return confirm('<?php
                  echo $this->__('Are you sure you would like to remove this item from the wishlist?') ?>');" class="btn-remove"><?php
                   echo $this->__('Remove This Item') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php
                 echo $this->escapeHtml($product->getName()) ?></a></p>
                <?php if ($product->isSaleable() && $product->isVisibleInSiteVisibility()): ?>
                    <a href="<?php echo $this->getItemAddToCartUrl($_item) ?>" class="link-cart"><?php
                     echo $this->__('Add to Cart') ?></a>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($product, false, '-wishlist') ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('wishlist-sidebar');</script>
    <div class="actions">
        <a href="<?php echo $this->helper('wishlist')->getListUrl() ?>"><?php
         echo $this->__('Go to Wishlist') ?></a>
    </div>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
    <?php endif ?>
    </div>
</div>

