<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php 
/**
 * Get Item
 */
$_item = $this->getItem() ?>
<?php $_order = $this->getItem()->getOrderItem()->getOrder() ?>
<tr class="border" id="order-item-row-<?php echo $_item->getId() ?>">
<td><h4 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h4>
    <?php 
    /**
     * Check options equal to itemoptions
     */
    if ($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <?php 
                /**
                 * Check print status has not been set
                 */
                if (!$this->getPrintStatus()): ?>
                    <?php 
                    /**
                     * Get Formated option value
                     */
                    $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dd<?php 
                    /**
                     * Check formated option value full view has been set
                     */
                    if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php
                     echo $_formatedOptionValue['value'] ?>
                        <?php 
                        /**
                         * Check full view of formated option value has been set
                         */
                     ?>
                            <div class="truncated_full_value">
                                <dl class="item-options">
                                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                    <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                </dl>
                            </div>
                       
                    </dd>
                <?php else: ?>
                    <dd><?php 
                    /**
                     * Check print value has been set
                     * if it is display the print value
                     * else display the option normal value
                     */
                    echo $this->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php 
    /**
     * Get add info of block
     */
    $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
    <?php 
    /**
     * Check add info block has been already set
     */
    if ($addInfoBlock) : ?>
        <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
    <?php endif; ?>
    <?php echo $this->escapeHtml($_item->getDescription()) ?>
    <?php 
    /**
     * Check Gift Message Available
     * and gift message id has been set
     */
    if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item->getOrderItem()) && $_item->getGiftMessageId()): ?>
        <a href="#" id="order-item-gift-message-link-<?php echo $_item->getId() ?>" class="gift-message-link"
           onclick="return giftMessageToogle('<?php echo $_item->getId() ?>')"><?php
            echo $this->__('Gift Message') ?></a>
    <?php endif; ?>
</td>
<td data-rwd-label="<?php echo $this->__('SKU') ?>"><?php
 echo $this->escapeHtml(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>
<td data-rwd-label="<?php echo $this->__('Price') ?>"
class="a-right" >
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
    <span class="price-excl-tax">
                <?php 
                if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <?php 
                    if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price">
                    <?php endif; ?>
                    <span class="label">
                    <?php echo $this->__('Excl. Tax'); ?>:</span>
                    <?php
                     if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
        <span class="cart-tax-total"
              onclick="taxToggle('eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
            <span class="cart-price">
                <?php endif; ?>
              <?php 
                 if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <?php
                     echo $this->getOrder()->formatPrice($this->getItem()->getPrice() + $this->getItem()->getWeeeTaxAppliedAmount() + $this->getItem()->getWeeeTaxDisposition()); ?>
                <?php
                 else:
                  ?>
                    <?php 
                    echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
                <?php
                 endif;
                  ?>
             </span>
 <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>
<span class="cart-tax-info" 
                id="eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>"
                      style="display:none;">
                        <?php 
                        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr">
                                    <?php echo $tax['title']; ?>
                                        : <?php $tAmt= $this->getOrder()->formatPrice($tax['amount']);
                                        echo $tAmt; ?></span>
                                <?php endforeach; ?>
                            </small>
                        <?php 
                        elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php 
                            foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr">
                                <small><?php echo $tax['title']; ?>
                                        : <?php $tAmt= $this->getOrder()->formatPrice($tax['amount']); 
                                        echo $tAmt;?></small></span>
                            <?php endforeach;
                             ?>
                        <?php
                         elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>
                                        : <?php $tAmt= $this->getOrder()->formatPrice($tax['amount']); 
                                        echo $tAmt;?></span>
                                <?php endforeach; ?>
                            </small>
                         <?php else :
                         echo '';
                         ?>    
                        <?php endif; ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total"
                          onclick="taxToggle('eunit-item-tax-details<?php 
                          $ids= $this->getItem()->getId();
                          echo $ids; ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>
                                :<br/> <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice() + $this->getItem()->getWeeeTaxAppliedAmount() + $this->getItem()->getWeeeTaxDisposition()); ?></span>
                        </span>
                <?php endif; ?>
            <?php endif; ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
        <span class="price-incl-tax">
                <?php 
                if ($this->helper('tax')->displaySalesBothPrices()): 
                ?>
                    <?php 
                    if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()):
                     ?>
                        <span class="cart-price">
                    <?php endif;
                     ?>
                    <span class="label">
                    <?php echo $this->__('Incl. Tax');
                     ?>:
                    </span>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()):
                     ?>
                        </span>
                    <?php endif;
                     ?>
                <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($this->getItem()); ?>
            <?php 
            if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total"
                  onclick="taxToggle('unit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                <span class="cart-price">
                <?php endif; ?>
                <?php 
                if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <?php 
                    echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                <?php
                 else: ?>
                    <?php
                     echo $this->getOrder()->formatPrice($_incl - $this->getItem()->getWeeeTaxDisposition()) ?>
                <?php endif; ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="unit-item-tax-details<?php echo $this->getItem()->getId(); ?>"
                          style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php 
                                foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr">
                                    <?php echo $tax['title']; ?>
                                        : <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?></span>
                                <?php endforeach; ?>
                            </small>
                        <?php
                         elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr">
                                <small><?php echo $tax['title']; ?>
                                        : <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?></small></span>
                            <?php endforeach; ?>
                        <?php
                         elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php 
                                foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr">
                                    <?php 
                                    echo $tax['title']; ?>
                                        : <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?></span>
                                <?php
                                 endforeach; ?>
                            </small>
                         <?php else :
                         echo '';
                         ?> 
                        <?php 
                        endif; ?>
                    </span>
             <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total"
                              onclick="taxToggle('unit-item-tax-details<?php 
                              echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr">
                            <?php 
                            echo Mage::helper('weee')->__('Total incl. tax'); 
                            ?>
                                :<br/> 
                                <?php 
                                echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); 
                                ?>
                                </span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?></span>
            <?php endif; ?></td>
<?php 
/**
 * Display Item Quantity
 */
?>
<td class="a-center"
 data-rwd-label="<?php echo $this->__('Qty') ?>">
 <?php
 echo $_item->getQty() * 1 ?>
 </td>
<td class="a-right" 
data-rwd-label="<?php echo $this->__('Subtotal') 
?>">
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
    <span class="price-excl-tax">
                <?php
                 if ($this->helper('tax')->displaySalesBothPrices()): 
                 ?>
                    <?php 
                    if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): 
                    ?>
                        <span class="cart-price">
                    <?php
                     endif;
                      ?>
                    <span class="label">
                    <?php 
                    echo $this->__('Excl. Tax'); 
                    ?>:</span>
                    <?php
                     if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): 
                     ?>
                        </span>
                    <?php
                     endif;
                     ?>
                <?php 
                endif;
                 ?>
        <?php 
        if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
        <span class="cart-tax-total"
              onclick="taxToggle('esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
            <span class="cart-price">
                <?php endif; ?>
<?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <?php
                     echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal() + $this->getItem()->getWeeeTaxAppliedRowAmount() + $this->getItem()->getWeeeTaxRowDisposition()); ?>
                <?php else:
                 ?>
                    <?php 
                    echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
                <?php endif; 
                ?>

                </span>


            <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                <span class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>"
                      style="display:none;">
                        <?php
                         if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php 
                                foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr"><?php
                                     echo $tax['title']; ?>
                                        : <?php 
                                        echo $this->getOrder()->formatPrice($tax['row_amount']); ?></span>
                                <?php
                                 endforeach; ?>
                            </small>
                        <?php 
                        elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php
                             foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr">
                                <small>
                                <?php
                                 echo $tax['title']; ?>
                                        : <?php 
                                        echo $this->getOrder()->formatPrice($tax['row_amount']); ?></small></span>
                            <?php
                             endforeach;
                             ?>
                        <?php 
                        elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php 
                                foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr">
                                    <?php 
                                    echo $tax['title']; ?>
                                        : <?php
                                         echo $this->getOrder()->formatPrice($tax['row_amount']); ?></span>
                                <?php 
                                endforeach; ?>
                            </small>
                         <?php else :
                         echo '';
                         ?> 
                        <?php endif; ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total"
                          onclick="taxToggle('esubtotal-item-tax-details<?php
                           echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr">
                            <?php echo Mage::helper('weee')->__('Total'); ?>
                                :<br/>
                                 <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal() + $this->getItem()->getWeeeTaxAppliedRowAmount() + $this->getItem()->getWeeeTaxRowDisposition()); ?></span>
                        </span>
                <?php endif; ?>
            <?php endif; ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php 
        /**
         * Check display both prices has been set
         * or sales price including tax has been set
         */
        if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
        <span class="price-incl-tax">
                <?php 
                if ($this->helper('tax')->displaySalesBothPrices()){
                 ?>
                    <?php
                     if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                        <span class="cart-price">
                    <?php 
                  }
                    ?>
                    <span class="label">
                    <?php 
                    echo $this->__('Incl. Tax'); 
                    ?>:</span>
                    <?php 
                    if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()){ ?>
                        </span>
                    <?php
                    }
                     ?>
                <?php 
             }
                ?>
            <?php
             $_incl = $this->helper('checkout')->getSubtotalInclTax($this->getItem());
              ?>
            <?php
             if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total"
                  onclick="taxToggle('subtotal-item-tax-details<?php
                   echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                <span class="cart-price">
                <?php 
                endif; ?>
                <?php
                 if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <?php
                     echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                <?php
                 else: ?>
                    <?php 
                    echo $this->getOrder()->formatPrice($_incl - $this->getItem()->getWeeeTaxRowDisposition()) ?>
                <?php 
                endif; ?>
                </span>
             <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>
     <span class="cart-tax-info"
      id="subtotal-item-tax-details<?php 
      echo $this->getItem()->getId(); ?>"
                          style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php
                                 foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr">
                                    <?php echo $tax['title']; ?>
                                        : <?php
                                         echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></span>
                                <?php endforeach; ?>
                            </small>
                        <?php
                         elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php
                             foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr">
                                <small>
                                <?php echo $tax['title']; 
                                ?>
                                        : <?php 
                                        echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></small></span>
                            <?php endforeach; ?>
                        <?php 
                        elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                    <span class="nobr">
                                    <?php echo $tax['title'];
                                     ?>
                                        : <?php 
                                         echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></span>
                                <?php endforeach;
                                 ?>
                            </small>
                        <?php else :
                         echo '';
                         ?> 
                        <?php endif; ?>
                    </span>
                 <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total"
                              onclick="taxToggle('subtotal-item-tax-details<?php 
                              echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr">
                            <?php
                             echo Mage::helper('weee')->__('Total incl. tax'); 
                             ?>
                                :<br/>
                                 <?php
                                  echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
             </span>
            <?php endif; ?>
</td>
<?php
/**
 * Display Discount amount
 */
?>
<td class="a-right" data-rwd-label="<?php echo $this->__('Discount Amount') ?>"><?php
 echo $_order->formatPrice(-$_item->getDiscountAmount()) ?>
 </td>
 <?php 
 /**
  * Display total
  */
 ?>
<td class="last a-right" data-rwd-label="<?php echo $this->__('Row Total') ?>">
    <?php echo $_order->formatPrice($_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount() + $_item->getWeeeTaxAppliedRowAmount()) ?>
</td></tr>
