<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */

/**
 * @deprecated  after 1.4.0.0-alpha3
 */
?>
<?php 
$item = $this->getItem() ?>
<tr>
    <td class="a-center"><a href="<?php echo $this->getItemDeleteUrl($item) ?>" 
    title="<?php echo $this->__('Remove Item')?>" class="btn-remove2">
    <?php echo $this->__('Remove Item')?></a></td>
    <td><a href="<?php echo $this->getItemUrl($item) ?>" 
    title="<?php echo $this->escapeHtml($this->getItemName($item)) ?>" class="product-image">
    <img src="<?php echo $this->helper('catalog/image')->init($this->getItemProductForThumbnail($item), 'thumbnail')->resize(75); ?>" width="75" 
    alt="<?php echo $this->escapeHtml($this->getItemName($item)) ?>" /></a></td>
    <td>
        <h3 class="product-name"><a href="<?php echo $this->getItemUrl($item) ?>">
        <?php echo $this->getItemName($item) ?></a></h3>
        <?php echo $this->getItemDescription($item) ?>
        <?php if($item->getMessage()): ?>
            <p class="item-msg <?php if($item->getHasError()): ?>error
            <?php else: ?>notice<?php endif; ?>">* 
            <?php echo $item->getMessage() ?></p>
        <?php endif; ?>
    </td>
    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <td class="a-center">
        <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($item->getId()); ?>" class="link-wishlist">
        <?php echo $this->__('Move'); ?></a>
    </td>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()) ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getPriceInclTax($item)); ?>
    </td>
    <?php endif; ?>
    <td class="a-center">
        <input type="text" pattern="\d*" name="cart[<?php echo $item->getId() ?>][qty]" 
        value="<?php echo $this->getItemQty($item) ?>" size="4" class="input-text qty" maxlength="12" />
    </td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()) ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
    </td>
    <?php endif; ?>
</tr>
