<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="quick-view-category">
    <?php
$quickViewCategoryCollection = $this->getQuickview ();
$categoryCount = count ( $quickViewCategoryCollection );
if ($categoryCount >= 1) { ?>

<p><?php echo $this->__('Quick Links')?>
<span><?php echo $this->__('-')?></span></p>
<ul>
<?php foreach ( $quickViewCategoryCollection as $_quickViewCategoryCollection ) {?>
<li>
<a href="<?php echo Mage::getBaseUrl().$_quickViewCategoryCollection->getUrlPath();?>" title="Quick View">

<?php
$prName = $_quickViewCategoryCollection->getName();
$lenPrName = strlen($_quickViewCategoryCollection->getName());
$subPrName = substr($prName, 0, 12);
if ($lenPrName >= 12) {
$prNameFix = $subPrName . "...";
} else {
$prNameFix = $prName;
}
echo $prNameFix;
?>

</a>
</li>
<?php } ?>
</ul>
<?php } ?>
</div>
  