<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?> 
<?php 

/**
 * get seller id
 */
$id = $this->getRequest()->getParam('id');

/**
 * display product collection
 */
$sellerPage = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);
$countryData = str_replace(" ", "+",$sellerPage->getCountry());
$stateData = str_replace(" ", "+",$sellerPage->getState());

$urlData = 'http://maps.google.com/maps/api/geocode/json?address="'.$stateData.'"&sensor=false&region="'.$countryData.'"';
$response = file_get_contents($urlData);
$response = json_decode($response, true);

$lat = $long = ''; 
if(isset($response['results'][0]['geometry']['location']['lng'])){
    $long = $response['results'][0]['geometry']['location']['lng'];
}
if(isset($response['results'][0]['geometry']['location']['lat'])){
$lat = $response['results'][0]['geometry']['location']['lat'];
}
if(!empty($lat) && !empty($long)){
    $googleApiKey='';
    $googleApiKey=Mage::getStoreConfig("marketplace/marketplace/google_id");
    
?> 
<?php 
if (isset($_SERVER['HTTPS']) &&
        ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) ||
        isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
        $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
            $protocol = 'https';
        }
        else {
            $protocol = 'http';
        }
?>
<?php if($protocol=="https"){?>
 <script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $googleApiKey;?>"></script>
 <?php }else{?>
  <script src="http://maps.googleapis.com/maps/api/js?key=<?php echo $googleApiKey;?>"></script>
     
<?php }?>
    <script>
    var myCenter=new google.maps.LatLng(<?php echo $lat; ?>,<?php
    	     echo $long;?>);
    
      function initialize() {
        var mapCanvas = document.getElementById("map_canvas");
        var mapOptions = {
          center: myCenter,
          zoom: 5,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions);
        var marker=new google.maps.Marker({
            position:myCenter,
            });

          marker.setMap(map);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<div class="block">
<div class="block-title"><strong><span><?php echo $this->__('Store Location');?></span></strong></div>
<div class="block-content"><div id="map_canvas"  style="width:235px;height:235px"></div></div>
</div>
<?php } ?>

