<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <?php if( $this->isExpanded() ): ?>
        <div class="sorter">
            <?php if( $this->isEnabledViewSwitcher() ): ?>
                <p class="view-mode">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                        <label><?php echo $this->__('View as') ?></label>
                        <?php foreach ($this->getModes() as $_code=>$_label): ?>
                            <?php if($this->isModeActive($_code)): ?>
                                <strong title="<?php echo $_label ?>" 
                                class="<?php echo strtolower($_code); ?>">
                                <?php echo $_label ?></strong>
                            <?php else: ?>
                                <a href="<?php echo $this->getModeUrl($_code) ?>" 
                                title="<?php echo $_label ?>" 
                                class="<?php echo strtolower($_code); ?>">
                                <?php echo $_label ?></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </p>
            <?php endif; ?>

            <div class="sort-by">
                <label><?php echo $this->__('Sort By') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo $this->__('Sort By') ?>">
                    <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                        <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"
                        <?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                            <?php echo $this->__($_order) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <?php if($this->getCurrentDirection() == 'desc'): ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" class="sort-by-switcher sort-by-switcher--desc" 
                    title="<?php echo $this->__('Set Ascending Direction') ?>">
                    <?php echo $this->__('Set Ascending Direction') ?></a>
                <?php else: ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" class="sort-by-switcher sort-by-switcher--asc" 
                    title="<?php echo $this->__('Set Descending Direction') ?>">
                    <?php echo $this->__('Set Descending Direction') ?></a>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="pager">
        <div class="count-container">
            <?php if($this->getLastPageNum()>1): ?>
                <p class="amount amount--has-pages">
                    <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                </p>
            <?php else: ?>
                <p class="amount amount--no-pages">
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                </p>
            <?php endif; ?>

            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo $this->__('Results per page'); ?>">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"
                    <?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>
        </div>

        <?php echo $this->getPagerHtml() ?>

    </div>
</div>
<?php endif ?>
