<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */ 
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    
<?php $products = $this->getItemCollection()->getItems();?>
    <?php $this->resetItemsIterator() ?>
    <div class="products-grid <?php if(count($products)>4){
    echo 'slider-carousel'; 
    } 
    else {
   echo 'no-slider'; 
    } ?>">
    <?php foreach ($this->getItemCollection()->getItems() as $_link): ?>
    <?php 
    $originalPrice = $_link->getPrice(); 
    $discountPrice = $_link->getSpecialPrice(); 
    $savings = $originalPrice - $discountPrice; 
    $savingsPercentage = round(($savings / $originalPrice) * 100, 0);?>
   <div class="slider">        
            <a href="<?php echo $_link->getProductUrl() ?>" 
            title="<?php echo $this->escapeHtml($_link->getName()) ?>" class="product-image">
                <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(260) ?>" 
                alt="<?php echo $this->escapeHtml($_link->getName()) ?>" />
            </a>
            <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" 
            title="<?php echo $this->escapeHtml($_link->getName()) ?>">
            <?php echo $this->escapeHtml($_link->getName()) ?></a></h3>
            <?php echo $this->getReviewsSummaryHtml($_link, false, true)?>
            <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
           
        <div class="actions">
			  <?php 
			if($_link->isSaleable()){ ?>
			                       <?php                        /**
			                        * Check the product is saleable
			                        * if so then display the option add to cart
			                        * else show out of stock message
			                        */?>
			                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart animated fadeIn" 
			                        onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_link) ?>')">
			<span><span><?php echo $this->__('Add to Cart') ?></span></span>
			</button>
			                    <?php } 
			                    else {?>
			                        <p class="availability out-of-stock animated fadeIn">
			<span>
			<?php echo $this->__('Out of stock') ?></span>
			</p>
			                   <?php } ?>
			<ul class="add-to-links">
			<li>
			<a href="<?php echo $this->helper('wishlist')->getAddUrl($_link) ?>"
			title="<?php echo $this->__('Add to Wishlist') ?>"
			class="link-wishlist animated fadeIn">
			<?php echo $this->__('Add to Wishlist') ?>
			</a>
			</li>
			<li>
			<span class="separator">|
			</span> 
			<a href="<?php 
			echo Mage::helper('catalog/product_compare')->getAddUrl($_link);
			?>" class="link-compare animated fadeIn" title="<?php echo $this->__('Add to Compare') ?>">
			<?php echo $this->__('Add to Compare') ?>
			</a>
			</li>
			</ul>
			<a class="button-action"><span class="plus"></span></a>               
			
			                   </div>  
       
      </div>
    <?php endforeach; ?>
   </div>
</div>
<?php endif ?>
 <script type="text/javascript">
  $mp = jQuery.noConflict();
  $mp(document).ready(function(){
$mp('.slider-carousel').bxSlider({
    slideWidth: 300,
    minSlides: 2,
    maxSlides: 4,
    moveSlides: 1,
    slideMargin: 10
  });
});
</script>