<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php

$_item = $this->getItem();
/**
 * Assign Repeated values to variables
 */
$isvisibleProductAvail = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<tr>
<?php
/**
 * Product Cart Image Section
 * Display Product Cart Image with thumbnail
 */
?>
<td class="product-cart-image">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>" 
            title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image">
        <?php endif;?>
            <img src="<?php echo $this->getProductThumbnail()->resize(180); ?>" 
            alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
        <?php if ($this->hasProductUrl()):?>
            </a>
        <?php endif;?>
        <?php
        /**
        * Display Product Cart Links
        */
        ?>
        <ul class="cart-links">
            <?php 
            /**
             * Check the product is set as visible
             */
            if ($isvisibleProductAvail): ?>
                <li>
                    <a href="<?php echo $this->getConfigureUrl() ?>" 
                    title="<?php echo $this->__('Edit Item') ?>">
                    <?php echo $this->__('Edit') ?></a>
                </li>
            <?php endif ?>

            <?php 
            /**
             * Check the wishlist allow in cart and is visible product
             */
            if ($this->helper('wishlist')->isAllowInCart() && $isvisibleProductAvail) : ?>
                <li>
                    <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax">
                    <?php echo $this->__('Move to wishlist'); ?></a>
                </li>
            <?php endif ?>
        </ul>
    </td>
    <?php 
    /**
     * Product Information Section
     * Display product name
     * sku
     * product options
     */
    ?>
    <td class="product-cart-info">

        <a href="<?php echo $this->getDeleteUrl() ?>" 
        title="<?php echo $this->__('Remove Item') ?>" class="btn-remove btn-remove2">
        <?php echo $this->__('Remove Item') ?></a>

        <h2 class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>">
            <?php echo $this->escapeHtml($this->getProductName()) ?></a>
        <?php else: ?>
            <?php echo $this->escapeHtml($this->getProductName()) ?>
        <?php endif; ?>
        </h2>

        <div class="product-cart-sku">
            <span class="label"><?php echo $this->__('SKU'); ?>:</span> 
            <?php echo $this->escapeHtml($_item->getSku()); ?>
        </div>

        <?php if ($optionsInfoList = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($optionsInfoList as $_option) : ?>
            <?php $_OptionValues = $this->getFormatedOptionValue($_option) ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <dd<?php if (isset($_OptionValues['full_view'])): ?> class="truncated"<?php endif; ?>>
                <?php echo $_OptionValues['value'] ?>
                <?php if (isset($_OptionValues['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd><?php echo $_OptionValues['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>

        <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?php echo $message['type'] ?>">
                * <?php echo $this->escapeHtml($message['text']) ?>
            </p>
        <?php endforeach; ?>
        <?php endif; ?>

        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>

    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="a-center product-cart-price"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link">
                <?php echo $this->__("What's this?"); ?></a>

                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php
                     echo $this->__("What&#39;s this?") ?>");
                </script>

            </span>
        </td>
    <?php else: ?>

        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="product-cart-price" 
        data-rwd-label="<?php echo $this->__('Price'); ?>" 
        data-rwd-tax-label="<?php echo $this->__('Excl. Tax'); ?>">
      <?php 
      if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" 
                onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php 
            endif; ?>
                <?php 
                if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php 
                    echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                <?php 
                else: ?>
                    <?php
                     echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                <?php endif;
                 ?>
       </span>
   <?php if (Mage::helper('weee')->getApplied($_item)):
    ?>
       <div class="cart-tax-info" 
       id="eunit-item-tax-details<?php 
       echo $_item->getId(); 
       ?>" 
       style="display:none;">
               <?php 
               if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){?>
                        <?php
                         foreach (Mage::helper('weee')->getApplied($_item) as $tax): 
                         ?>
                            <span class="weee">
                            <?php 
                            echo $tax['title']; 
                            ?>: 
                            <?php
                             echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?>
                             </span>
                        <?php
                        endforeach; 
                        ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee">
                            <?php 
                             echo $tax['title']; ?>: 
                            <?php  
                            echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php 
                        foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee">
                            <?php  
                            echo $tax['title']; ?>: 
                            <?php 
                             echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                        <?php endforeach; ?>
                    <?php } ?>
                </div>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()):
         ?>
                    <div class="cart-tax-total"
                     onclick="taxToggle('eunit-item-tax-details<?php 
                     echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee">
                        <?php 
                        echo Mage::helper('weee')->__('Total'); ?>: 
                        <?php
                         echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <?php endif; ?><!-- inclusive price starts here -->
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="product-cart-price" data-rwd-label="<?php echo $this->__('Price'); ?>" 
        data-rwd-tax-label="<?php echo $this->__('Incl. Tax'); ?>">
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span
                 class="cart-tax-total"
                 onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>
                <?php
                 if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php 
                    echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                <?php
                 else: ?>
                    <?php 
                    echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                <?php endif; ?>

            </span>
            <?php if (Mage::helper('weee')->getApplied($_item)): 
           
            ?>
                <div class="cart-tax-info" id="unit-item-tax-details<?php 
                echo $_item->getId(); ?>" style="display:none;">
                    <?php 
                    if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php
                         foreach (Mage::helper('weee')->getApplied($_item) as $taxamt): ?>
                            <span class="weee">
                            <?php  
                            echo $taxamt['title']; ?>: 
                            <?php  
                              echo Mage::helper('checkout')->formatPrice($taxamt['amount_incl_tax'],true,true); ?></span>
                        <?php 
                        endforeach;
                         ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php
                         foreach (Mage::helper('weee')->getApplied($_item) as $taxPrice): ?>
                            <span class="weee">
                            <?php 
                            echo $taxPrice['title']; ?>: 
                            <?php
                             echo Mage::helper('checkout')->formatPrice($taxPrice['amount_incl_tax'],true,true); ?></span>
                        <?php 
                        endforeach;
                         ?>
                    <?php }
                    if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                        <?php
                        foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee">
                            <?php 
                            echo $tax['title']; ?>: 
                            <?php
                             echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                        <?php 
                        endforeach; ?>
                    <?php } ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee">
                        <?php 
                        echo Mage::helper('weee')->__('Total incl. tax'); ?>: 
                        <?php
                         echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <?php endif; ?>
    <?php endif; ?>
    <?php 
    /**
     * Display Product Cart Options
     */
    ?>
    <td class="product-cart-actions" data-rwd-label="<?php echo $this->__('Qty'); ?>">
        <input type="text" pattern="\d*" name="cart[<?php echo $_item->getId() ?>][qty]" 
        value="<?php echo $this->getQty() ?>" size="4" 
        title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" />

        <button type="submit" 
        name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update'); ?>" class="button btn-update">
        <span><span><?php echo $this->__('Update'); ?></span></span>
        </button>
        <?php
        /**
        * Display cart links
        */
        ?>
        <ul class="cart-links">
            <?php 
            /**
             * Check if product is set as visible product
             */
            if ($isvisibleProductAvail): ?>
                <li>
                    <a href="<?php echo $this->getConfigureUrl() ?>" 
                    title="<?php echo $this->__('Edit Item') ?>">
                    <?php echo $this->__('Edit') ?></a>
                </li>
            <?php endif ?>

            <?php 
            /**
             * Check wishlist is allow in cart
             */
            if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <li>
                <?php 
                /**
                 * Check the product is set as visible
                 */
                if ($isvisibleProductAvail): ?>
                    <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax">
                    <?php echo $this->__('Move to wishlist'); ?></a>
                <?php endif ?>
            </li>
            <?php endif ?>
        </ul>

    </td>

    <!--Sub total starts here -->
    <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="product-cart-total" data-rwd-label="<?php echo $this->__('Subtotal'); ?>">

      <?php 
      if ($canApplyMsrp):
              ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php 
            else:
             ?>
                <?php 
                if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php
                     echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                <?php else: ?>
                    <?php
                     echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                <?php endif; ?>
            <?php endif; ?>

        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" 
            id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" 
            style="display:none;">

                <?php 
                if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){
                     ?>
                    <?php
                     foreach (Mage::helper('weee')->getApplied($_item) as $taxData):
                      ?>
                        <span class="weee">
                        <?php 
                        echo $taxData['title']; 
                        ?>: 
                        <?php
                         echo Mage::helper('checkout')->formatPrice($taxData['row_amount'],true,true); ?></span>
                    <?php endforeach;
                     ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ 
                      ?>
                    <?php
                     foreach (Mage::helper('weee')->getApplied($_item) as $tax): 
                    ?>
                        <span class="weee">
                        <?php 
                        echo $tax['title'];
                         ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true);
                         ?>
                        </span>
                    <?php endforeach;
                     ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){
                      ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="weee">
                        <?php 
                        echo
                         $tax['title'];
                         ?>: 
                        <?php
                         echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?>
                         </span>
                    <?php endforeach; 
                    ?>
                <?php } ?>
            </div>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div 
                class="cart-tax-total" 
                onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="weee">
                    <?php 
                    echo Mage::helper('weee')->__('Total'); ?>: 
                    <?php
                     echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="product-cart-total" data-rwd-label="<?php echo $this->__('Subtotal'); ?>">
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" 
            onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php
         endif; 
         ?>
      <?php 
      if ($canApplyMsrp):
       ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php
             else:
              ?>
                <?php
                 if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php
                     echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                <?php 
                else:
                 ?>
                    <?php
                     echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php 
                endif;
                 ?>
            <?php
             endif;
              ?>
  </span>
    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
        <div class="cart-tax-info" style="display:none;"
            id="subtotal-item-tax-details<?php echo $_item->getId(); ?>"
             >
           <?php 
                if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ 
                   ?>
                  <?php 
                    foreach (Mage::helper('weee')->getApplied($_item) as $taxDetail):
                     ?>
                        <span class="weee">
                        <?php
                         echo $taxDetail['title']; ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($taxDetail['row_amount_incl_tax'],true,true); ?></span>
                    <?php
                     endforeach; ?>
               <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                 <?php 
                    foreach (Mage::helper('weee')->getApplied($_item) as $taxList): 
                    ?>
                        <span class="weee">
                        <?php 
                        echo $taxList['title'];
                         ?>: 
                        <?php
                         echo Mage::helper('checkout')->formatPrice($taxList['row_amount_incl_tax'],true,true); ?></span>
                    <?php
                     endforeach;
                      ?>

                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
  <?php
   foreach (Mage::helper('weee')->getApplied($_item) as $taxInfo): 
   ?>
                        <span class="weee">
                        <?php 
                        echo $taxInfo['title'];
                         ?>: 
                        <?php 
                        echo Mage::helper('checkout')->formatPrice($taxInfo['row_amount_incl_tax'],true,true); ?></span>
                    <?php endforeach;
                     ?>
                <?php } ?>
            </div>
          <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" 
                onclick="taxToggle('subtotal-item-tax-details<?php
                 echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="weee">
                    <?php 
                    echo Mage::helper('weee')->__('Total incl. tax'); 
                    ?>: 
                    <?php
                     echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); 
                     ?></span> </div>
            <?php endif; ?>
        <?php endif; ?></td>
    <?php endif; ?>
    <?php 
    /**
     * Display product Remove option from cart
     */
    ?>
    <td class="a-center product-cart-remove">
        <a href="<?php echo $this->getDeleteUrl() ?>" 
        title="<?php echo $this->__('Remove Item') ?>" class="btn-remove btn-remove2">
        <?php echo $this->__('Remove Item') ?></a>
    </td>
</tr>


