<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */

/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */


$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
<?php if ($product->isSaleable()): ?>
    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="addWItemToCart(<?php
     echo $item->getId()?>);" class="button btn-cart">
     <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p class="availability in-stock">
            <span class="label">
            <?php 
            echo $this->helper('catalog')->__('Availability:') ?>
            </span>
            <span class="value">
            <?php 
            echo $this->helper('catalog')->__('In stock') ?>
            </span>
        </p>
    <?php else: ?>
        <p class="availability out-of-stock">
            <span class="label">
            <?php echo $this->helper('catalog')->__('Availability:') ?>
            </span>
            <span class="value">
            <?php echo $this->helper('catalog')->__('Out of stock') ?>
            </span>
        </p>
    <?php endif; ?>
<?php endif; ?>
</div>
<?php if ($product->isVisibleInSiteVisibility()): ?>
    <p><a class="link-edit button button-secondary" href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php
     echo $this->__('Edit') ?></a></p>
<?php endif ?>
<?php foreach($this->getSortedChildren() as $childName):?>
    <?php echo $this->getChildHtml($childName, false);?>
<?php endforeach;?>
</div>
