<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php 


$_item = $this->getItem()?>
<tr>
<?php
/**
 * Display Product name with options
 *
 */
?>
    <td><h3 class="product-name"><?php echo $this->escapeHtml($this->getProductName()) ?></h3>
        <!-- item custom options -->
        <?php if ($_optionsList = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_optionsList as $_option) : ?>
            <?php $_formatedOptionsInfo = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionsInfo['full_view'])): ?> class="truncated"<?php endif; ?>>
            <?php echo $_formatedOptionsInfo['value'] ?>
                <?php if (isset($_formatedOptionsInfo['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionsInfo['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
        <?php if ($links = $this->getLinks()): ?>
        <dl class="item-options">
            <dt><?php echo $this->getLinksTitle() ?></dt>
            <?php foreach ($links as $link): ?>
                <dd><?php echo $this->escapeHtml($link->getTitle()); ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <!-- EOF downloadable -->
    </td>
    <?php 
    /**
     * Display Product Price with tax information
     *
     */
    if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right" data-rwd-label="<?php echo $this->__('Price') ?>">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" 
            onclick="taxToggle('eunit-item-tax-details<?php 
             $itemId=$_item->getId(); 
             echo $itemId; ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php $calculatedPrice= $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); 
                echo $calculatedPrice;?>
            <?php else: ?>
                <?php $calculatedPrice= $this->helper('checkout')->formatPrice($_item->getCalculationPrice());
                echo $calculatedPrice; ?>
            <?php endif; ?>

        </span>


        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php $formattedAmt= Mage::helper('checkout')->formatPrice($tax['amount'],true,true);
                    echo $formattedAmt;?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: 
                        <?php $formattedtaxAmt= Mage::helper('checkout')->formatPrice($tax['amount'],true,true);
                        echo $formattedtaxAmt; ?></small></span><br />
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php $amt= Mage::helper('checkout')->formatPrice($tax['amount'],true,true);
                        echo $amt; ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php } ?>
            </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div
                 class="cart-tax-total" 
                onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> 
                    <?php $priceData= $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition());
                    echo $priceData; ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td 
    data-rwd-label="<?php echo $this->__('Price') ?>">
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span 
            class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php 
            $_itemId= $_item->getId(); 
            echo $_itemId; ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php $_inclPrice= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); 
                echo $_inclPrice;?>
            <?php else: ?>
                <?php $_inclPrice= $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition());
                echo $_inclPrice; ?>
            <?php endif; ?>

        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php
                         $taxAmount= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true);
                         echo $taxAmount; ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: 
                        <?php $amtInclPrice= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true);
                        echo $amtInclPrice; ?></small></span><br />
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php $amtInclPrice= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); 
                        echo $amtInclPrice;?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php } ?>
            </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> 
                    <?php $totalPrice= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); 
                    echo $totalPrice;
                    ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <td class="a-center" data-rwd-label="<?php echo $this->__('Qty') ?>">
    <?php echo $_item->getQty() ?></td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right" data-rwd-label="<?php echo $this->__('Subtotal') ?>">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
      <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php $rowTotal= $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition());
                echo $rowTotal; ?>
            <?php else: ?>
                <?php $rowTotal= $this->helper('checkout')->formatPrice($_item->getRowTotal());
              echo $rowTotal;   ?>
            <?php endif; ?>

        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php $rowAmt= Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); 
                        echo $rowAmt;?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: 
                        <?php $formattedrowAmt= Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true);
                        echo $formattedrowAmt; ?></small></span><br />
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php $priceInfo= Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true);
                        echo $priceInfo; ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php } ?>
            </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div 
                class="cart-tax-total" 
                onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr">
                    <?php echo Mage::helper('weee')->__('Total'); ?>:
                    <br /> 
                    <?php $totalAmt= $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition());
                    echo $totalAmt; ?></span></div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td data-rwd-label="<?php echo $this->__('Subtotal') ?>">
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span 
            class="cart-tax-total"
             onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php $includedPrice= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item));
                echo $includedPrice; ?>
            <?php else: ?>
                <?php $includedPrice= $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition());
               echo $includedPrice;  ?>
            <?php endif; ?>

        </span>
<?php if (Mage::helper('weee')->getApplied($_item)): ?>

            <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php $subtotal= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); 
                        echo $subtotal;?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: 
                        <?php $subtotal= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); 
                        echo $subtotal;?></small></span><br />
                    <?php endforeach; ?>
                <?php }
                if (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()){ ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: 
                        <?php $subtotal= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true);
                        echo $subtotal; ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php } ?>
            </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div
                 class="cart-tax-total" 
                onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr">
                    <?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> 
                    <?php $subtotal= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item));
                    echo $subtotal; ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
</tr>
