<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php

    $itemData = $this->getItem();
    $isVisibleProduct = $itemData->getProduct()->isVisibleInSiteVisibility();
    $ApplyMsrp = Mage::helper('catalog')->canApplyMsrp($itemData->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item">
<?php 
/**
 * Get Product Url
 */?>
    <?php if ($this->hasProductUrl()): ?>
        <a href="<?php echo $this->getProductUrl()?>" 
        title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image">
        <img src="<?php echo $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10'); ?>" width="50" height="50" 
        alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
    <?php else: ?>
    <?php 
    /**
    Get Product Image
    */
    ?>
        <span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10'); ?>" width="50" height="50" 
        alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></span>
    <?php endif; ?>
    <div class="product-details">
        <a href="<?php echo $this->getDeleteUrl() ?>" 
        title="<?php echo $this->__('Remove This Item') ?>" 
        onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>');" class="btn-remove"><?php
         echo $this->__('Remove This Item') ?></a>
        <p class="product-name"><?php if ($this->hasProductUrl()): ?>
        <a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?>
        <?php echo $this->escapeHtml($this->getProductName()) ?>
        <?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
        <?php if ($isVisibleProduct): ?>
        <a href="<?php echo $this->getConfigureUrl() ?>" 
        title="<?php echo $this->__('Edit item') ?>" class="btn-edit">
        <?php echo $this->__('Edit item')?></a>
        <?php endif ?>
        <strong><?php echo $this->getQty() ?></strong> x

    <?php if ($ApplyMsrp): ?>

        <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>

    <?php else: ?>

    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <?php echo $this->__('Excl. Tax'); ?>:
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($itemData, array(0, 1, 4), 'sales')): ?>
            <?php echo $this->helper('checkout')->formatPrice($itemData->getCalculationPrice()+$itemData->getWeeeTaxAppliedAmount()+$itemData->getWeeeTaxDisposition()); ?>
        <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($itemData->getCalculationPrice()) ?>
        <?php endif; ?>
        <?php if (Mage::helper('weee')->getApplied($itemData)): ?><br />
            <?php if (Mage::helper('weee')->typeOfDisplay($itemData, 1, 'sales')){ ?>
                <small>
                <?php foreach (Mage::helper('weee')->getApplied($itemData) as $tax): ?>
                    <span class="nobr">
                    <?php echo $tax['title']; ?>: 
                    <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?>
                    </span><br />
                <?php endforeach; ?>
                </small>
            <?php }
            if (Mage::helper('weee')->typeOfDisplay($itemData, 2, 'sales')){ ?>
                <?php foreach (Mage::helper('weee')->getApplied($itemData) as $tax): ?>
                    <span class="nobr">
                    <small><?php echo $tax['title']; ?>: 
                    <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                <?php endforeach; ?>
            <?php }
            if (Mage::helper('weee')->typeOfDisplay($itemData, 4, 'sales')){ ?>
                <small>
                <?php foreach (Mage::helper('weee')->getApplied($itemData) as $tax): ?>
                    <span class="nobr">
                    <?php echo $tax['title']; ?>: 
                    <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                <?php endforeach; ?>
                </small>
            <?php } ?>
            
            <?php if (Mage::helper('weee')->typeOfDisplay($itemData, 2, 'sales')): ?>
                <span class="nobr">
                
                <?php echo Mage::helper('weee')->__('Total'); ?>:
                <br /> 
                <?php echo $this->helper('checkout')->formatPrice($itemData->getCalculationPrice()+$itemData->getWeeeTaxAppliedAmount()+$itemData->getWeeeTaxDisposition()); ?></span>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
 <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($itemData); ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <br /><?php echo $this->__('Incl. Tax'); ?>:
        <?php endif; ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($itemData, array(0, 1, 4), 'sales')): ?>
            <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($itemData)); ?>
        <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($_incl-$itemData->getWeeeTaxDisposition()) ?>
        <?php endif; ?>
        <?php if (Mage::helper('weee')->getApplied($itemData)): ?>
            <br />
            <?php if (Mage::helper('weee')->typeOfDisplay($itemData, 1, 'sales')){ ?>
                <small>
                <?php foreach (Mage::helper('weee')->getApplied($itemData) as $tax): ?>
                    <span class="nobr"><?php echo $tax['title']; ?>: 
                    <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                <?php endforeach; ?>
                </small>
            <?php }
            if (Mage::helper('weee')->typeOfDisplay($itemData, 2, 'sales')){ ?>
                <?php foreach (Mage::helper('weee')->getApplied($itemData) as $tax): ?>
                    <span class="nobr"><small><?php echo $tax['title']; ?>: 
                    <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                <?php endforeach; ?>
            <?php }
            if (Mage::helper('weee')->typeOfDisplay($itemData, 4, 'sales')){ ?>
                <small>
                <?php foreach (Mage::helper('weee')->getApplied($itemData) as $tax): ?>
                    <span class="nobr"><?php echo $tax['title']; ?>: 
                    <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                <?php endforeach; ?>
                </small>
            <?php } ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($itemData, 2, 'sales')): ?>
                <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> 
                <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($itemData)); ?></span>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>

    <?php endif; ?>

        <?php if ($_options = $this->getOptionList()):?>
        <div class="truncated">
          <div class="truncated_full_value">
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <dd>
                    <?php if (is_array($_option['value'])): ?>
                    <?php echo nl2br(implode("\n", $_option['value'])) ?>
                    <?php else: ?>
                    <?php echo $_option['value'] ?>
                    <?php endif; ?>
                </dd>
                <?php endforeach; ?>
            </dl>
          </div>
        <a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a>
        </div>
        <?php endif; ?>
    </div>
</li>
