<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Change Account Password') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $action ?>" method="post" id="form-validate" class="scaffold-form">
<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Change Account Password') ?></h2>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <ul class="form-list">
        <li>
            <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
            <div class="input-box">
                <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text required-entry" name="current_password" id="current_password" />
            </div>
        </li>
        <li class="fields"><div class="field">
                <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                <div class="input-box">
                    <input  title="<?php echo $this->__('New Password') ?>" type="password" class="input-text required-entry validate-password" name="password" id="password" />
                </div>
            </div>
            <div class="field">
                <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                <div class="input-box"><input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small>
    <?php echo $this->__('Back') ?></a></p>
    <button type="submit" title="<?php echo $this->__('Save Password') ?>" class="button">
    <span><span><?php echo $this->__('Save Password') ?></span></span></button>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate');
//]]>
</script>
