<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.9.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php if ($_productsDetails = $this->getRecentlyComparedProducts()): ?>
<div class="widget widget-compared">
    <div class="widget-title">
        <h2><?php echo $this->__('Recently Compared') ?></h2>
    </div>
    <div class="widget-products">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; ?>
        <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
            <?php foreach ($_productsDetails as $product): ?>
                <li class="item<?php if(($i-1)%$_columnCount==0){ ?> first<?php }else{                
                 if($i%$_columnCount==0){ ?> last<?php }
} ?>">
                    <?php $_imgSize = 210; ?>
                    <a href="<?php echo $product->getProductUrl() ?>" title="<?php
                     echo $this->stripTags($product->getName(), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize($_imgSize) ?>" alt="<?php
                         echo $this->stripTags($product->getName(), null, true) ?>" />
                    </a>
                    <div class="product-info">
                        <h3 class="product-name">
                        <a href="<?php echo $product->getProductUrl() ?>" title="<?php
                         echo $this->stripTags($product->getName(), null, true) ?>)"><?php
                          echo $this->helper('catalog/output')->productAttribute($product, $product->getName() , 'name') ?></a></h3>
                        <?php echo $this->getPriceHtml($product, true, '-widget-compared-grid') ?>
                        <?php echo $this->getReviewsSummaryHtml($product, 'short') ?>
                        <div class="actions">
                            <?php if($product->isSaleable()): ?>
                                <button type="button"
                                title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                                 onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')">
                                 <span><span><?php echo $this->__('Add to Cart') ?></span>
                                 </span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->getAddToWishlistUrl($product) ?>" class="link-wishlist"><?php
                                     echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if($compareUrl = $this->getAddToCompareUrl($product)): ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $compareUrl ?>" class="link-compare"><?php
                                     echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
